Adding in nitrogen surface training reactions
ReactionMechanismGenerator/RMG-database pull request #390
Opened 2020-03-12 15:42 UTC by mazeau

These came from Micro-kinetic modeling of NH3 decomposition on Ni and
its application to solid oxide fuel cells
From Deutschmann et al
doi: 10.1016/j.ces.2011.07.007

2020-10-08 12:37 UTC, nateharms requested changes
You're basically adding a few reactions for adsorption of nitrogen species to surfaces. I have a few comments but overall, looks good

2020-10-08 12:37 UTC, nateharms commented on input/kinetics/libraries/Surface/Nitrogen/dictionary.txt
> +2 X u0 p0 c0 {1,D}
Should there be a new line at the end of a dictionary? Wondering on the basis of formatting.

2020-10-08 12:37 UTC, nateharms commented on input/kinetics/libraries/Surface/Nitrogen/reactions.py
> +    index = 2,
I'm kind of confused by the indexing for the reactions here. @mazeau could you explain this a little?

2020-10-08 15:37 UTC, mazeau commented on input/kinetics/libraries/Surface/Nitrogen/reactions.py
> +    index = 2,
index relates to the reaction number in the paper

2020-10-08 15:37 UTC, mazeau commented on input/kinetics/libraries/Surface/Nitrogen/dictionary.txt
> +2 X u0 p0 c0 {1,D}
I can add one

2020-10-19 21:42 UTC, nateharms approved these changes
Looks good to me. You addressed my one comment.

2020-10-20 15:34 UTC, merged