Distributing catalytic deutschmann rates into vdw families
ReactionMechanismGenerator/RMG-database pull request #447
Opened 2020-11-09 21:37 UTC by mazeau

Now that the new vdw families have been merged in, this PR distributes the rates from the deutschmann library to their corresponding vdw family as training reactions.

this is related to https://github.com/ReactionMechanismGenerator/RMG-database/issues/430 and https://github.com/comocheng/wiki/issues/614

2020-11-11 17:59 UTC, mazeau commented
oops I forgot to add ranks

2020-11-14 19:40 UTC, kblondal requested changes

2020-11-14 19:40 UTC, kblondal commented on input/kinetics/families/Surface_Adsorption_vdW/training/reactions.py
> +        A = 7.0E-6,
Any reason why it is not the same value as in the paper? In the paper S0=8.0E-3 for R11.

2020-11-14 19:40 UTC, kblondal commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +    label = "CH4* + Cu4 <=> CH3* + H*",
I think we should use more generic names than "Cu4" for surface sites since the training reactions are on various metals.

2020-11-14 19:40 UTC, kblondal commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +        A = (1.52E17,'cm^2/(mol*s)'),
This is not the same value as in the paper (1.54E21 cm2/(mol*s)) for R13.

2020-11-15 21:14 UTC, mazeau commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +        A = (1.52E17,'cm^2/(mol*s)'),
the paper uses m^2 /mol*s so I just converted

2020-11-15 21:18 UTC, mazeau commented on input/kinetics/families/Surface_Adsorption_vdW/training/reactions.py
> +        A = 7.0E-6,
good catch! thanks

2020-11-15 21:21 UTC, mazeau commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +    label = "CH4* + Cu4 <=> CH3* + H*",
Good idea, thanks

2020-11-15 21:39 UTC, mazeau commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +        A = (1.52E17,'cm^2/(mol*s)'),
fixed unit typo!

2020-11-16 16:27 UTC, kblondal approved these changes
Looks good to me!

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +#         Ea=(218400), 'J/mol'),
I know it's commented out, but there's an extra (or missing) parenthesis, and that seems dangerous.

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        Ea=(92700, 'J/mol'),
Very low priority, but there should probably be spaces around the = sign for consistency: Ea = (92700, 'J/mol'). Perhaps a global find and replace can fix it everywhere else.

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        Tmax = (3000, 'K'),
Where does this temperature range come from? I'm mostly asking for myself because I don't know how this works. I skimmed the Delgado et al paper and the only temperature range I could find was 373-1123 K. Are we listing it as [200,3000] because RMG won't let us use the estimate outside the listed range?

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        A = (5.622E20, 'm^2/(mol*s)'),
I think there's an extra 2 in this parameter, A, and it should be  5.62E20.

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +        A = (1.52E17,'m^2/(mol*s)'),
I think A is supposed to be 1.54E17

2020-11-16 22:32 UTC, sevyharris commented on input/kinetics/families/Surface_Dissociation_Double_vdW/training/reactions.py
> +#         A=(4.64E19, 'm^2/(mol*s)'),
If you're doing a global find and replace to make the spacing consistent, you should add 'A=' to the search in addition to 'Ea=' because it appears a couple of times. (I wish I could offer you more substantive comments, but this is my first week with RMG, so, yeah, fix the spacing!)

2020-11-16 22:37 UTC, mazeau commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        Tmax = (3000, 'K'),
The temperature range was what we had used before

2020-11-18 17:17 UTC, mazeau commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        A = (5.622E20, 'm^2/(mol*s)'),
good catch!

2020-11-18 17:22 UTC, mazeau commented on input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
> +        A = (1.52E17,'m^2/(mol*s)'),
yep!

2020-11-18 17:25 UTC, mazeau commented on input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
> +        Ea=(92700, 'J/mol'),
gotcha

2020-11-19 14:13 UTC, merged