Adding Surface_Dissociation_Double family
ReactionMechanismGenerator/RMG-database pull request #458
Opened 2021-03-13 01:09 UTC by Tingchenlee

The family is for a gas-phase double-bonded species dissociatively adsorbing to the surface with double bonds with the following template:
```
*2=*3                      *2          *3
        +          ---->   ||    +     ||
~*1~        ~*4~          ~*1~        ~*4~
```
After trying this family locally, the following reactions were shown:
![image](https://user-images.githubusercontent.com/56702445/111013616-05b01880-836e-11eb-82e5-9a94bca16df4.png)
![image](https://user-images.githubusercontent.com/56702445/111013641-22e4e700-836e-11eb-9836-5998e27a2784.png)

Some of the reactions already existed in our surface libraries, and hopefully, we can add them to the training with this family.

2021-03-15 18:22 UTC, rwest commented on input/kinetics/families/Surface_Dissociation_Double/groups.py
> +*2=*3                      *2          *3
Please update this to be more like
```
*2=*3                                     *2          *3
           +           +          ---->   ||    +     ||
               ~*1~        ~*4~          ~*1~        ~*4~
```

2021-03-15 18:23 UTC, rwest commented
Maybe it should be called something like `Surface_Adsorption_Dissociative_Double` ?

2021-03-15 18:51 UTC, Tingchenlee commented
Yeah, I agree with that. I wasn't sure should we name it Surface_Adsorption_Dissociative_Double or Surface_Dissociation_Double at the time I built this. The rule.py was taken from Surface_Adsorption_Dissociative and the recipe was from Surface_Dissociation_Double_vdW

2021-03-15 22:02 UTC, mazeau requested changes
I am happy with this! Just change the name in all the places and it'll be good to merge in I think.

2021-03-15 22:02 UTC, mazeau commented on input/kinetics/families/recommended.py
> +    'Surface_Dissociation_Double',
Don't forget to also change the name here

2021-03-15 22:02 UTC, mazeau commented on input/kinetics/families/Surface_Dissociation_Double/training/reactions.py
> +name = "Surface_Dissociation_Double/training"
I definitely agree with richard about changing the name of this family to Surface Adsorption Associative Double

2021-03-15 23:38 UTC, Tingchenlee commented on input/kinetics/families/Surface_Dissociation_Double/rules.py
> +        E0 = (10, 'kcal/mol'),
It's from Surface_Adsorption_Dissociative. Maybe we could add more entries in the rule.py? For example, the O2 reaction from Deutschmann?

2021-03-25 02:19 UTC, Tingchenlee commented on input/kinetics/families/Surface_Dissociation_Double/rules.py
> +        E0 = (10, 'kcal/mol'),
I Added the O2 reaction from Deutschmann into rules.py

2021-03-25 13:39 UTC, rwest commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/rules.py
> +    metal = 'Ni'
@mazeau can/should rule entries have metal attributes, or is it only training reactions for now?

2021-03-25 20:58 UTC, rwest commented
As revealed by the tests, it turns out we can't put `metal` attribute on a family rule (only on a training reaction) so I reverted that commit. I then squashed the other commits, as they were all just corrections. Rebased and force-pushed.

2021-03-25 21:02 UTC, mazeau commented
> As revealed by the tests, it turns out we can't put `metal` attribute on a family rule (only on a training reaction) so I reverted that commit. I then squashed the other commits, as they were all just corrections. Rebased and force-pushed.

Hmmm don't we also not ever use rules anymore? We switched to only using training reactions?

2021-03-29 19:29 UTC, mazeau approved these changes
Looks good to me! Don't forget to add the picture representation into `families/images` and rerun the script `scripts/process_family_images.py` to add it to `rmg_reaction_families.pdf`

2021-03-30 00:33 UTC, Tingchenlee commented
Is there specific software for drawing the picture?
![image](https://user-images.githubusercontent.com/56702445/112915820-33ff5900-90cd-11eb-9e74-ae0070f6970f.png)

I made this but I am not sure if it is acceptable.

2021-03-31 01:38 UTC, ChrisBNEU commented
I might have already asked this, but were we going to include any other training reactions/rate rules? I thought we had at least 1 or two other ones besides O2 Dissociative adsorption that fit this template (like co2 dissociative adsorption from the deutschmann_ni library)

2021-03-31 16:10 UTC, ChrisBNEU commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/training/reactions.py
> +#!/usr/bin/env python
@mazeau  said we can add in reactions from Deutschmann. so CO2 dissociative adsorption can be added in.

2021-03-31 17:58 UTC, Tingchenlee commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/training/reactions.py
> +#!/usr/bin/env python
I added three training reactions and deleted the rules.py one

2021-04-01 00:29 UTC, ChrisBNEU commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/training/reactions.py
> +#!/usr/bin/env python
turns out they are the wrong reaction type, they are not sticking coefficient, they are both surface arrhenius and they cause a bunch of database tests to fail. My fault. If you revert the changes I will approve so we can push this through and I'll figure out how to add them in a separate PR.

2021-04-01 00:44 UTC, Tingchenlee commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/training/reactions.py
> +#!/usr/bin/env python
okay I delete them now and we can wait for the testing

2021-04-01 16:18 UTC, rwest commented
Should have noticed this earlier. Oxygen in the gas phase is by default triplet ground state and should be a biradical .O-O.  or the SMILES `[O][O]`, not the double bonded `O=O`, and hence should not, by default, occur in this family.

That is to say, if you have two `O=X` adsorbates on the surface and they recombine and leave they should leave as `[O][O]` not `O=O`. And if you have oxygen in the gas phase it will be represented as `[O][O]` which is what you want to be dissociatively adsorbing to the surface. 

See [documentation section 10.1 ](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/species.html#representing-oxygen).

Occasionally people have singlet oxygen in the gas phase, but it has to be explicitly allowed. I'm not sure, **do we want to create it (and react it) with this family if it *is* explicitly allowed?**  if so, how do we estimate its production rate?

2021-04-01 18:35 UTC, alongd commented
I think that the `allowSingletO2=False` input file option only allows/disallows users to give `O=O` as an input file species, so RMG complaints if one tries to combust a fuel with singlet O2 by mistake. But singlet O2 is always allowed in the model itself. Maybe we should allow both `X=O + X=O <=> 2X + O=O` and `X=O + X=O <=> 2X + [O][O]`. Probably the Ea for the first one will be limited by the endothermic products?

2021-04-01 20:24 UTC, mazeau commented
I think we should keep the O2 dissociative adsorption separate in its own library and forbid it from doing this here.

2021-04-05 16:46 UTC, Tingchenlee commented
I hid the singlet O=O entry and added the forbidden block, and it passed the database test on my local RMG-Py master branch.
![image](https://user-images.githubusercontent.com/56702445/113599549-c7281980-960c-11eb-8910-3a9659dcc912.png)

2021-04-05 18:08 UTC, davidfarinajr requested changes
looks good @Tingchenlee !  I think we need to change `p1` to `p0` for carbon atom in the `NC` entry, then I will approve the merge

2021-04-05 18:31 UTC, Tingchenlee commented on input/kinetics/families/Surface_Adsorption_Dissociative_Double/groups.py
> +2 *3 C  u0 p1 c0 {1,D}
Thanks, David, I think it should be p0! I just changed it.

2021-04-06 16:00 UTC, davidfarinajr approved these changes
Looks good! Thanks @Tingchenlee for adding this new family!

2021-04-07 14:39 UTC, ChrisBNEU approved these changes
Looks good to me. I ran this with out our [methanol model](https://github.com/comocheng/meOH-synthesis) on copper, the [Methane-steam](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/master/examples/rmg/catalysis/methane_steam) reforming on Ni model, and the [CH4 O2](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/master/examples/rmg/catalysis/ch4_o2) model on Pt. The reactions generated for both the core and edge seemed reasonable.

2021-04-14 19:36 UTC, merged