added CU111 thermo library for Vdw H2
ReactionMechanismGenerator/RMG-database pull request #516
Opened 2021-08-05 12:48 UTC by ChrisBNEU

### Description
I added thermo for the H2Vdw species on copper from the following paper: 
[On the hydrogen adsorption and dissociation on Cu surfaces and nanorows](https://doi.org/10.1016/j.susc.2015.08.005)

I scaled the enthalpy NASA polynomial values as follows (also included in the long description).
```
DFT binding energy on Pt111: -0.054 eV.
DFT binfing energy on Cu111: -0.08 eV. 
delta BE: -0.054 - (-0.08) = +0.026 eV = 0.026 eV * (1.602176565e-19 J/eV) * (6.02214*10^23) = 2508 J/mol

a5_low = -1.86700333*10^3 + (2508 J/mol) / (8.3145 J/mol K) = -1.565287266E+03
a5_high = -1.89107687*10^3 + (2508 J/mol) / (8.3145 J/mol K) = -1.589360806E+03
```
### Testing
Check the math above. This change has slightly improved out methanol on copper model, because the previous binding energy predicted more H2 VdW species, which does not agree with other literature models. 

equilibrium constant for H2 + X <=> H2X 
before: 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/56306881/128351321-0134a2c3-3fa3-4d11-80d4-61daac4832c4.png">

after: 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/56306881/128351410-7b84cc3d-c3a3-4c28-b81c-20a13f7ec641.png">

2021-08-06 16:04 UTC, davidfarinajr requested changes
<img width="743" alt="Screen Shot 2021-08-06 at 11 59 04 AM" src="https://user-images.githubusercontent.com/32377555/128538693-76f24ddc-fdc1-4248-9396-7a19723a8226.png">
Looks good Chris, except I think we shifted the enthalpy in the wrong direction.  If the DFT binding energy on Cu111 is greater (more negative), the enthalpy should be less (more negative) on Cu111 then on Pt111, but it looks like its greater.  Looks like we just need to subtract the `delta BE` rather than add it (or add it and calculate the delta as -0.08 - - 0.054 = -0.026).  In any case, the a5 coefficient should be less for Cu

2021-08-13 02:37 UTC, ChrisBNEU commented
I agree with David's comments, I have amended the values.

2021-08-13 17:16 UTC, davidfarinajr approved these changes

2021-09-20 22:39 UTC, mazeau approved these changes
Looks like this is also time to merge, thanks chrispy

2024-03-07 17:41 UTC, closed without merging