Fix labels, structures, and reactions for C:3 H:2 species in CurranPentane
ReactionMechanismGenerator/RMG-database pull request #551
Opened 2021-12-06 09:50 UTC by mefuller

Errors in label and structures for H2C3 isomers in the CurranPentane library are corrected:
- Previously omitted species H2CCC is added back
- C3H2 is updated to C#C[CH] from C=C=[C] (evolves from propargyl)
- All reactions for C3H2, C3H2(S), H2CCC(S), C3H2C (three-member ring) are checked and reassigned as needed

2021-12-06 16:55 UTC, sevyharris requested changes
Thank you for making these updates! I think there's one typo and one addition left to be made, but otherwise this looks great. Also, I'm happy to make the corrections later tonight if you don't have time to get to them today.

2021-12-06 16:55 UTC, sevyharris commented on input/kinetics/libraries/CurranPentane/reactions.py
> +    label = "C3H3 + H <=> C3H2C + H2",
I think this one is supposed to be
label = "C3H3 + H <=> H2CCC(S)+ H2"
based on the coefficients of the three Arrhenius's below and comparing to the yaml file (reaction 916)

2021-12-06 16:55 UTC, sevyharris commented on input/kinetics/libraries/CurranPentane/reactions.py
I think we're also missing Reaction #924:

entry(
    index = 3092,
    label = "H2CCC(S) + O2 <=> CO2 + C2H2",
    degeneracy = 1,
    kinetics = Arrhenius(A=(1e+13, 'cm^3/(mol*s)'), n=0, Ea=(0, 'cal/mol'), T0=(1, 'K')),
    shortDesc = u"""""",
)

2021-12-06 17:46 UTC, mefuller commented on input/kinetics/libraries/CurranPentane/reactions.py
Thanks for the review - I'll fix these up and push in a few hours

2021-12-06 21:22 UTC, mefuller commented on input/kinetics/libraries/CurranPentane/reactions.py
> +    label = "C3H3 + H <=> C3H2C + H2",
Good catch - thanks

2021-12-06 21:31 UTC, mefuller commented on input/kinetics/libraries/CurranPentane/reactions.py
Yup - added as R#3093

2021-12-07 01:57 UTC, sevyharris approved these changes
Looks good, thanks!

2021-12-07 15:25 UTC, mefuller commented
@sevyharris there was an accidental duplicate in reactions 846 and 848 that got missed: we had two C3H2C when one should have been H2CCC

2021-12-07 16:43 UTC, sevyharris commented
I got a little sidetracked during the developer hours meeting today, but I'll take a look at the most recent changes and see if Matt or David can merge it in this week.

2021-12-07 22:43 UTC, sevyharris commented
The changes look good to me! I also tested it and can confirm that this fixes the [issue ](https://github.com/ReactionMechanismGenerator/RMG-database/issues/526)I was running into before. I'll see if I can get someone with merge privileges to incorporate the changes.

2021-12-14 15:28 UTC, mefuller commented
@markpayne thank you and will do.
I don't see an option to change the PR source, so I will close this one and open another

2021-12-14 15:28 UTC, closed without merging