k_low and T1, T3 corrected
ReactionMechanismGenerator/RMG-database pull request #612
Opened 2023-03-10 01:42 UTC by agi-jaguar

Klippenstein_Glaborg_2016 and NOx_2018 CH3OH -> CH2(S) + H2O's low pressure k has been corrected. Also, T1 and T3 for Troe format have been corrected

2023-03-10 16:33 UTC, xiaoruiDong requested changes
@agi-jaguar Thanks for making the correction. I checked the predicted ks from these new numbers and they look pretty close to the ks from Jasper et al. (original source).

One suggestion before merging this in. Can you add a comment in `LongDesc` (add it after the `shortDesc` about this change...). In the comment, I think you should mention:

1. These entries have different numbers than the entries in the original mechanism files from the KG2016 and NOx2018 paper. Include the original numbers in the KG2016, NOx2018.
2. The reason about the change. (E.g., these numbers are adapted from Jasper et al., but the authors missed multiplying Na.)

In the PR, can you also include a plot showing how this changes the prediction of ks, and probably compared with the ks from Jasper et al.? This can be a good reference for future developers about this data change.

2023-03-11 02:00 UTC, agi-jaguar commented
<img width="927" alt="image" src="https://user-images.githubusercontent.com/122506860/224459024-5d70c0e1-8af1-4080-8319-e6c35b7ad2d6.png">

2023-03-13 00:24 UTC, agi-jaguar commented
I also made changed to Nitrogen_Glaborg_Jimenez as below

The reference of this reaction (Davis et al. , J. Phys. Chem. A 1999, 103, 5889-589910.1021/jp982762a) reported PdepArrhenius reaction information. However, RMG database (Nitrogen_Glaborg_Jimenez_ only contained the rate coefficient at 1 atm, so reported all of them (0.1, 1.0, 10, 100 atm)

2023-03-13 03:09 UTC, xiaoruiDong approved these changes
LGTM

2023-03-13 16:02 UTC, xiaoruiDong commented
@agi-jaguar Sorry that I changed my review. Can you
1. rebase the branch on the current `main`
2. squash the commits into two commits with more informative branch messages:
- combine the two `k_low_corrected` commits to "Correct CH3OH=CH2(S)+H2O Troe kinetics in two libraries"
- combine `pdeparrhenius added`, `unit corrected`, and `typo erased` commits to  "update C2H2+CH3=CH2CHCH2 with pdep kinetics"

I will approve your PR and merge it afterward.

2023-03-13 16:02 UTC, xiaoruiDong requested changes
See my last comments

2023-03-13 19:32 UTC, xiaoruiDong approved these changes

2023-03-14 17:11 UTC, xiaoruiDong requested changes
Thank you for finding another issue. Plz see my comments

2023-03-14 17:11 UTC, xiaoruiDong commented on input/kinetics/libraries/NOx2018/reactions.py
> +            Arrhenius(A=(8.3476e+20, 'cm^3/(mol*s)'), n=-4, Ea=(0, 'cal/mol'), T0=(1, 'K')),
Can you add a description of the change you made (basically, *P/RT) and a reference to issue #613 in the new commit you added, so the future developer has a better understanding of the change?

2023-03-20 02:01 UTC, xiaoruiDong commented on input/kinetics/libraries/Klippenstein_Glarborg2016/reactions.py
> +    number since the number in the original paper has the unit of molecule rather than mol )"""
Noticed a parenthesis was forgot to removed at the end. And I suggest a 
longDesc = u"""This entry has different numbers than the entries in the mechanism files (Hashemi et al.).It uses the kinetic parameters from the original source (Jasper et al. J. Phys. Chem. A, 2007, 111, 19, 3932–3950). Jasper et al. reported kinetic unit in molecule, cm^3, and s, but Hashemi et al. didn't multiply the A factor of the low-pressure limit Arrhenius by Avogadro's number when compiling the mechanism (with the unit in mol, cm^3, and s). Besides, Hashemi et al. mistakenly reversed the order of the T1 and T3 parameters."""

2023-03-20 02:26 UTC, xiaoruiDong commented on input/kinetics/libraries/NOx2018/reactions.py
> +    k_0~ 7E-31300^3T^-3 [cm6/#2/s] * P/RT [#/cm3] = 7E-31300^31013.25/8.314E6*(6.02E23)^2 [cm6/#/s] = 8.348E+20*T^-4"""
longDesc = u"""This entry has different rate constants at P=0.01 atm than the entries in the mechanism file (Glarborg et al.). In Glarborg et al., k at 0.01 atm was taken from the low-pressure limit k0 from Fernandes et al. (Fernandes et al., JPCA, 110, 13, 4442-4449).  However, according to the definition by Fernandes et al., k0 (7E-31*(T/300)^-3 [cm6/#2/s]) has to be multiplied by [M] (P/RT) to get the rate constants at a specific pressure. Thus, k(P=0.01 atm) ~ 7E-31*(T/300)^-3 [cm6/#2/s] * P/RT [mol/cm3] = 7E-31*(300^3)*(6.02E23)^2*(1013.25/8.314E6)*(T^-4) [cm3/mol/s] = 8.348E+20*T^-4"""

2023-03-20 02:29 UTC, xiaoruiDong commented on input/kinetics/libraries/NOx2018/reactions.py
> +    number since the number in the original paper has the unit of molecule rather than mol )"""
longDesc = u"""This entry has different numbers than the entries in the mechanism file (Hashemi et al.).It uses the kinetic parameters from the original source (Jasper et al. J. Phys. Chem. A, 2007, 111, 19, 3932–3950). Jasper et al. reported kinetic unit in molecule, cm^3, and s, but Hashemi et al. didn't multiply the A factor of the low-pressure limit Arrhenius by Avogadro's number when compiling the mechanism (with the unit in mol, cm^3, and s). Besides, Hashemi et al. mistakenly reversed the order of the T1 and T3 parameters."""

2023-03-20 02:29 UTC, xiaoruiDong commented on input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/reactions.py
> +        ],
Sorry Jeehyun @agi-jaguar , do you have some time to also add a description here? Thanks.

2023-03-20 02:32 UTC, xiaoruiDong requested changes
Hi @agi-jaguar, Thank you so much for helping correct these numbers. It is really helpful! I left a few comments about correcting the description. I hope you understand that I want to make sure all the changes are trackable, understandable, and reproducible by future developers, and your effort is highly appreciated.

2023-03-20 04:46 UTC, agi-jaguar commented on input/kinetics/libraries/Nitrogen_Glarborg_Gimenez_et_al/reactions.py
> +        ],
No worries Jerry! I added the description!

2023-03-29 20:08 UTC, xiaoruiDong commented
@hwpang I have already checked the correction proposed by Jeehyun @agi-jaguar. However, Jeehyun is very busy and doesn't have time to update some of the descriptions I suggested. Therefore, I pushed a new commit to add more details to describe the correction of each modified entry in the corresponding "long description". Please let me know if you think these comments read okay and are understandable by other (potentially future) developers. Thanks!

2023-04-14 18:36 UTC, xiaoruiDong approved these changes

2023-04-14 18:36 UTC, merged