Added the NH3 thermo library
ReactionMechanismGenerator/RMG-database pull request #620
Opened 2023-05-20 17:41 UTC by alongd

Based on CCSD(T)-F12/cc-pVTZ-F12//B2PLYPD3/aug-cc-pVTZ computations
with enthalpies from ATcT where available

Also added `NcNOO` to the forbidden species and made two minor modifications to the `primaryNitrogenLibrary` kinetic library

2024-07-18 15:33 UTC, jonwzheng requested changes
Hi Alon, thank you and your team for this big update of the thermo database. It can be difficult and tedious work to search carefully through the literature - so once again, thank you for your effort!

Due to the large size of this PR, I will split my review into multiple stages. This will help me get feedback to you as soon as possible rather than all at once.

I double-checked the new data added in `primaryNitrogenLibrary`, `primaryNS`, `primaryH2O2` and `HydrazinePDep`. I started looking at `forbiddenStructures` but will continune in a future review. I haven't yet looked at `NH3` library. Here are my overall comments:

* We have some concerns about forbidding these structures; a species may exist even if it cannot be found at a certain QM LOT. If we forbid a structure that ends up being an important intermediate, this could dramatically - and silently - impair model performance. On Bill's suggestion, I've started commenting on those ones that may need additional discussion, as several pathways in principle seem reasonable for generating those species (and I will examine the rest of the reactions in a future review). Could you please comment about your thoughts on this issue?

* Many reactions had their kinetic data replaced with newer data, could you briefly comment on this - were such old data in serious error?

* Some of the data seem to be transcribed in error, please check out the individual line comments.

2024-07-18 15:33 UTC, jonwzheng commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc=u"""[Tsang1991]""",
seems to be reaction # 11,11 in Table 2
They report the same A-factor, but they report Ea/R = 1561 (or 3101 cal/mol) instead of 13000, could you please  check this?

2024-07-19 19:57 UTC, caochuangmit commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc = u"""[Klippenstein2022]""",
I check the original literature source and think Ea of the reaction `NH2 + HO2 <=> HNO + H2O` should be -938 cal/mol instead of -1864 cal/mol. Also, I believe the unit of R in Arrhenius equations shouldbe J mol−1 K−1 rather than cal mol−1 K−1 as stated in Klippenstein's work, after a test for another reaction (NH2+HO2=NH3+O2), where I use Klippenstein's fitted kinetic parameters to compare with the curve in figure 4 in their work.

2024-07-19 20:09 UTC, caochuangmit commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc = u"""[Klippenstein2022]""",
Please check Ea. I think for NH2+HO2 reactions calculated in Klippenstein2022, The Ea should be directly taken from the equations given in the main text and then converted to nagative values, without considering any unit conversions.

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +    longDesc =
It was determined in a previous work to be non-physical along with NNOOH
I added NNOOH now as well, and added a short justification for both of these molecules

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +A CBS-QB3 job was unable to optimize this structure, got NO + H2NO
We think that many -N-O- chains will be unstable (though not all).
There are many forbidden molecules here that were excluded based on one calculation, and more work should be done to verify. I'm OK with removing species that were ruled out based on just one computation. When generating the NH3 model, please check whether any of them are in the core or are in a PDep network that yielded a core reaction - if so an additional study should be done for them.

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +An wb97xd/def2svp conformer search was unable to optimize any of the conformer, they break down into O2 + H2NN
This was probably copied over, so probably the missing H in the comment is my typo. I had many of these and tried to give a lead to future studies on these species

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +A CBS-QB3 job was unable to optimize this structure, got HO2 + H2NO
Looks like my comments were inaccurate. I had many cases of these species and I may have written the comments in a rush. I'm OK with not merging these forbidden molecules, it's also not an elegant method to exclude them like that, perhaps a deeper study can come up with some rules of thumb and an on-the-fly QM analysis can validate whether they exist or not.

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +A CBS-QB3 job was unable to optimize this structure, got H2O + HNN
The comment wasn't meant for what could form this allegedly non-existing, it is meant to describe what the DFT opt gave - the species broke into these two fragments.

2024-07-20 18:35 UTC, alongd commented on input/kinetics/libraries/primaryH2O2/reactions.py
> +    No data was given, the rate is very low.
There was a change to the counting index above. number 41 is now number 40
The rate remained the same.

I renumbered now again this section to avoid skipping the running indices of 41, 42

Sorry that I didn't separate content changes from formatting and renumbering changes, I can try to separate it into two commits if it helps

2024-07-20 18:35 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +Also available from D&B, originally taken from:
Sure

2024-07-20 18:35 UTC, alongd commented on input/forbiddenStructures.py
> +    longDesc =
For `k2` in the table (LHS), B values are negative, the B values on the right are for `k5`

2024-07-20 19:28 UTC, alongd reviewed
Thanks for the helpful comments, and for actually checking the sources! Much appreciated.
Sorry for this huge PR.
Regarding the forbidden species, I'm open to remove most of them

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    Table S4 gives the raw data
Correct. I made the comment clearer now

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    kinetics=Arrhenius(A=(6.4e+07, 'cm^3/(mol*s)'), n=0, Ea=(77.1, 'kJ/mol'), T0=(1, 'K')),
Good catch, thanks!!

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +            Arrhenius(A=(1.31e-03, 'cm^3/(mol*s)'), n=-4.11, Ea=(-1938, 'cal/mol'), T0=(1, 'K'), Tmin=(300, 'K'), Tmax=(3000, 'K')),
Correct, `n` values should be positive here, I corrected.
Ea signs look good to me (look at the LHS for k3, not RHS for k_total)

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +            Arrhenius(A=(1.95e+06, 'cm^3/(mol*s)'), n=1.92, Ea=(-1312, 'cal/mol'), T0=(1, 'K'), Tmin=(300, 'K'), Tmax=(3000, 'K')),
All looks good to me here

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc=u"""[Tsang1991]""",
Correct, thanks!

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +Reinterpreted rate coefficient based on the Miller and Bowman's work (https://doi.org/10.1016/0360-1285(89)90017-8)
I referred to this text of Mei2019:
```
In this work, we estimated the rate constant of R7 from the evaluated result of Miller and Bowman [52]
with the energy barrier adjusted according to the calculated result of Klippenstein et al. [54].
The comparison of rate constants of R7 from different sources is shown in [Fig. 1](c).
```

The rate coeff is in the SI:
```
N2H2+M=NNH+H+M                                  3.80E+13	1.2	70100 ! PW ZXY_20190214 estimated from 1979 Miller PECS and the PES calculated by SJK2009 JPCA
```

2024-07-20 19:28 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    kinetics=Arrhenius(A=(1.5e+13, 'cm^3/(mol*s)'), n=0.0, Ea=(8012, 'cal/mol'),
I agree, my mistake.
Also, in the body of the paper that say `A<1.3e+13` and in the abstract `A<1.5e+13`, I'll adopt the lower number here

2024-07-20 19:31 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +            Arrhenius(A=(5.22e+37, 'cm^3/(mol*s)'), n=-8.46, Ea=(-4416, 'cal/mol'), T0=(1, 'K'), Tmin=(300, 'K'), Tmax=(3000, 'K')),
For `k2` in the table (LHS), B values are negative, the B values on the right are for `k5`

2024-07-20 19:36 UTC, alongd commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc = u"""[Klippenstein2022]""",
I agree, fixed, please see if correct now?

2024-07-20 21:58 UTC, ChgCao commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc = u"""[Klippenstein2022]""",
I think A=2.19e+09 and n=0.791 are correct, but Ea should be -1428 as expressed in R1c instead of -2838. Please double-check it.

2024-07-22 14:06 UTC, jonwzheng commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    kinetics=Arrhenius(A=(1.3e+13, 'cm^3/(mol*s)'), n=0.0, Ea=(58.8, 'kcal/mol'),
I think this should be 5.88 rather than 58.8 kcal/mol, could you please double check?

2024-07-22 15:23 UTC, jonwzheng commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    shortDesc=u"""[Cavallotti2023]""",
data from this source look good to me!

2024-07-22 17:54 UTC, jonwzheng commented
Thanks for checking the review comments. There are still a few small loose ends in the new library data, but those are just a matter of checking the original sources. I checked the `NH3` library and it looks okay to me.

The main question right now is whether we should merge the forbidden structures. I see the merit in excluding those potentially problematic species, but I also worry that some of them are real intermediates that could play a key role. One option is to _not_ forbid those structures, and then in our subsequent modeling work, see if they form in any appreciable amounts, and perhaps do a deeper analysis at that point. Is that what you suggested?  

Either is okay with me, but since this would affect the modeling workflow for the ammonia project, we should discuss with the team.

2024-07-22 18:19 UTC, alongd commented
@jonwzheng, I addressed the last comment on the PNL. Please let me know whether there are additional comments or whether I missed anything. I truly appreciate the time and effort of double-checking the values in this library, I know this is a relatively large PR that requires some time and effort to review.

I removed most of the forbidden species, let only two that were studied seriously.

I squashed the modifications, I think the PR is ready to be merged, of course let me know if there are any additional comments or concerns.

2024-07-22 18:27 UTC, jonwzheng commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    kinetics=Arrhenius(A=(1.3e+13, 'cm^3/(mol*s)'), n=0.0, Ea=(58.8, 'kcal/mol'),
My apologies, you're right!

2024-07-22 18:33 UTC, jonwzheng approved these changes
Just one comment about the index changing. 
Otherwise, looks good to me!

2024-07-22 18:33 UTC, jonwzheng commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    index=419,
My last comment is that the indexing changes since 417 and 418 were removed. I don't know whether this will make a practical difference, but best to make the indexing consistent anyway.

2024-07-25 02:35 UTC, ChgCao commented on input/kinetics/libraries/primaryNitrogenLibrary/reactions.py
> +    duplicate=True,
There are two reactions (this reaction and the last reaction) with index=432. Please move this reaction to the end and change the index number.

2024-07-27 10:10 UTC, alongd commented
@ChgCao, I updated the indices and squashed, if the tests pass I think we should be good to go

2024-07-29 19:48 UTC, jonwzheng commented
LGTM! but given the large scope @ChgCao could you also take a final look? If you approve, I'll go ahead and merge it in.

2024-07-30 14:12 UTC, merged