make adsorptionPt111 more flexible with lone pairs px
ReactionMechanismGenerator/RMG-database pull request #665
Opened 2024-09-18 17:25 UTC by bjkreitz

**Description**

The nodes in the adsorption correction file adsorptionPt111.py were rather restrictive. In most nodes it was specified that the general`R` cannot have lone pairs `p0`. I didn't pay close attention to this when I restructured the adsorption correction database because the `R` was mostly C in the training data. However, this is not correct. In most cases, the R can also be replaced with O/N. Actually, in some cases the training data that I used contained O, but the node would not have been used to estimate the thermo for this species. @kirkbadger18 caught this detail. 

I revised now the adjacency lists and made the nodes more permissive, by changing the `p0` to `px` whenever it is reasonable. 
I did not touch the nodes containing nitrogen, because @kirkbadger18 is doing a complete overhaul of the nitrogen adsorption corrections. 

**Testing**

I generated a mechanism for the oxidation of ethane on Pt(111) without (left log file) and with (right log file) these changes. The mechanisms are indeed slightly different. 

![Screenshot 2024-09-18 at 1 16 34 PM](https://github.com/user-attachments/assets/b8c97ace-a006-4719-a960-d6c36b37d716)

With the more permissible adsorption corrections, RMG deems a bidentate carboxyl to be important 

![Screenshot 2024-09-18 at 1 18 08 PM](https://github.com/user-attachments/assets/64285591-a9df-4dfb-8d2f-66e7c006cfcf)

Previously, this species was discovered, but remained in the edge. 

![Screenshot 2024-09-18 at 1 18 54 PM](https://github.com/user-attachments/assets/d9d752bd-7cef-4c95-8ee1-7fc5cf9b7bb5)

You see that the thermochemistry of the species has changed because RMG used the top level node `C*O*` to estimate the thermo and now it uses the more specific `C=*RO-*`. Whether this species should exist is another story (because there is also a monodentate carboxyl). However, I think that these updates to the adsorption corrections are necessary since they can affect our thermo estimate for some species and make them (supposedly) more accurate.  

**Review**
Carefully review that I haven't missed a node or an `R`. @kirkbadger18 will make another PR soon that changes the N-containing nodes. 
Generate a mechanism for system of your choice and check if everything works accordingly.

2024-09-23 21:17 UTC, kirkbadger18 commented on input/thermo/groups/adsorptionPt111.py
>  7 R  u0 p0 c0 {3,S}
I think this should be px too.

2024-12-03 21:41 UTC, rwest commented on input/thermo/groups/adsorptionPt111.py
>  7 R  u0 p0 c0 {3,S}
@kirkbadger18 or @bjkreitz  please confirm if this is still an issue. We should resolve and merge this pull request soon

2024-12-04 15:38 UTC, ChrisBNEU requested changes
I made a comment for a few species that may also need to have an R group with px. could just be me misunderstanding. I think if my comment and kirk's comment are addressed we should be good to rebase and merge if it passes the unit tests.

2024-12-04 15:38 UTC, ChrisBNEU commented on input/thermo/groups/adsorptionPt111.py
>  6 R  u0 p0 c0 {5,S}
Does this R get px as well? Also Rs for OROR on [lines 178-179](https://github.com/ReactionMechanismGenerator/RMG-database/blob/a0704a1cff50366a4c62a3b9a2372da22ca05850/input/thermo/groups/adsorptionPt111.py#L178), and O-*OR on [line 245](https://github.com/ReactionMechanismGenerator/RMG-database/blob/a0704a1cff50366a4c62a3b9a2372da22ca05850/input/thermo/groups/adsorptionPt111.py#L245)?

2024-12-04 16:22 UTC, bjkreitz commented on input/thermo/groups/adsorptionPt111.py
>  6 R  u0 p0 c0 {5,S}
Thanks Chris! I changed p0 to px for the C#*-R-C=*R, O-*OR, OROR

2024-12-04 16:23 UTC, bjkreitz commented on input/thermo/groups/adsorptionPt111.py
>  7 R  u0 p0 c0 {3,S}
I changed p0 to px for (CR3OR)*

2024-12-04 16:31 UTC, ChrisBNEU approved these changes
with the changes, as long as the unit tests pass this looks good to me

2024-12-04 16:49 UTC, rwest commented
Thanks Bjarne and Chris and Kirk. I enabled automerge. It should go in once the unit tests pass.

2024-12-04 18:56 UTC, merged